[OVMM] Update sim setup
facebookresearch/home-robot pull request #184
Opened 2023-05-16 15:03 UTC by yvsriram

## Motivation and Context

- Update assets link
- Update habitat sim version
- Update habitat-lab commit (now on object_rearrange)

## Changelog

## How Has This Been Tested

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

# Checklist:

- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] I ran `tests/hw_manual_test.py` on hardware and observed that robot behavior looks normal.

2023-05-16 17:24 UTC, yvsriram commented on src/home_robot_sim/environment.yml
> -  - habitat-sim==0.2.4
This is causing the tests to fail. I will fix this

2023-05-16 18:14 UTC, cpaxton reviewed
this all looks reasonable to me - @keke-220 can you test this and sign off if it looks reasonable to you, as a new user?

2023-05-17 16:05 UTC, keke-220 requested changes

2023-05-17 17:33 UTC, cpaxton commented on src/home_robot_sim/README.md
> +git submodule update --init --recursive
Is that better? i guess it means you have to enter a password every time you want to update...

2023-05-17 17:34 UTC, cpaxton commented on src/third_party/habitat-lab
confirming this is intentional

2023-05-17 22:27 UTC, keke-220 commented on src/home_robot_sim/README.md
> +git submodule update --init --recursive
Oh I thought it might be easier for external users to try it out but definitely let’s keep it as it is for us pushing updates easily

2023-05-18 14:18 UTC, yvsriram commented on README.md
> +cd habitat-sim
Thanks, I think it is best to point the users to BUILD_FROM_SOURCE.md, rather than repeating the instructions here. I made the change.

2023-05-18 14:21 UTC, keke-220 approved these changes

2023-05-18 14:25 UTC, yvsriram commented
I added habitat-sim as submodule. Currently the tests will fail. I will update CircleCI pipeline this weekend.

2023-05-18 16:30 UTC, merged