Karmeshyadav/robodev changes
facebookresearch/home-robot pull request #256
Opened 2023-06-29 00:02 UTC by ykarmesh

## Motivation and Context

Changes from the time of the real world experiments for OVMM.

## Changelog

## How Has This Been Tested

Tested in the real world

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

# Checklist:

- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] I ran `tests/hw_manual_test.py` on hardware and observed that robot behavior looks normal.

2023-06-29 13:52 UTC, cpaxton commented on projects/habitat_ovmm/configs/agent/nav_to_obj_rl.yaml
> +        action_distribution_type: "categorical"
no continuous version still?

2023-06-29 13:52 UTC, cpaxton commented on projects/habitat_ovmm/configs/agent/nav_to_obj_rl.yaml
> +        #action_dist:
Why is this commented out? should we leave an explanation for these fields?

2023-06-29 13:52 UTC, cpaxton commented on projects/habitat_ovmm/configs/agent/nav_to_obj_rl.yaml
> +        #action_dist:
Why is this commented out? Should we add a description for these fields?

2023-06-29 13:53 UTC, cpaxton commented on projects/habitat_ovmm/configs/agent/nav_to_obj_rl.yaml
> +        action_distribution_type: "categorical"
comment "gaussian or categorical" maybe?

2023-06-29 13:53 UTC, cpaxton commented on projects/habitat_ovmm/configs/agent/floorplanner_eval.yaml
> +      terminate_condition: discrete_stop
we need to document what these options do

2023-06-29 13:53 UTC, cpaxton commented on projects/stretch_ovmm/configs/agent/floorplanner_eval.yaml
> +  max_depth: 10.0         # maximum depth for depth sensor (in metres)
is this aligned with the robot?

2023-06-29 13:53 UTC, cpaxton commented on projects/stretch_ovmm/configs/agent/floorplanner_eval.yaml
> +      checkpoint_path: data/checkpoints/ovmm/May31/cat_gaze_recep_sensor_200m_may31.pth
are these checkpoints uploaded?

2023-06-29 13:59 UTC, cpaxton commented on projects/stretch_ovmm/configs/agent/floorplanner_eval.yaml
> +      type: rl # heuristic (default) or rl
Should we just create separate config files for RL vs Heuristic eval and pass them in on the command line?

2023-06-29 13:59 UTC, cpaxton commented on projects/stretch_ovmm/configs/agent/floorplanner_eval.yaml
> -        - ovmm_nav_goal_segmentation
not sure I understand this change

2023-06-29 14:02 UTC, cpaxton commented on src/home_robot/home_robot/motion/stretch.py
> +STRETCH_POSTNAV_Q = np.array(
wasn't this already added?

2023-06-29 14:02 UTC, cpaxton commented on src/home_robot_hw/home_robot_hw/env/visualizer.py
> +        vis_image = np.ones((655, 1600, 3)).astype(np.uint8) * 255
can you verify visualizations still look right?

2023-06-29 14:03 UTC, cpaxton commented on src/home_robot_hw/home_robot_hw/env/visualizer.py
> +        vis_image = np.ones((655, 2665, 3)).astype(np.uint8) * 255
same - maybe add screenshots?

2023-06-29 14:03 UTC, cpaxton commented on src/home_robot_hw/home_robot_hw/remote/modules/head.py
> +        # depth[depth < self.min_depth_val] = MIN_DEPTH_REPLACEMENT_VALUE
why is this function even called?

2023-06-29 14:03 UTC, cpaxton commented on src/home_robot_sim/home_robot_sim/env/habitat_objectnav_env/visualizer.py
> +        if rl_obs_frame is not None:
check visualizations?

2023-06-29 14:04 UTC, cpaxton requested changes
Some questions + want to make sure we commit working config files

2023-07-04 00:49 UTC, ykarmesh commented
Looks like all the changes from `robodev` were separately done on `main` by Sriram. Closing this PR

2023-07-04 00:50 UTC, closed without merging